parameters:
  app.huggingface_api_token: '%env(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)%'
  app.email_from: 'myapp@gmail.com'
  profile_image_directory: '%kernel.project_dir%/public/uploads/profile_images' # Make sure this is defined

  facepp.api_key: '%env(FACEPP_API_KEY)%'
  facepp.api_secret: '%env(FACEPP_API_SECRET)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Service\VoyageDescriptionIA:
    arguments:
      $parameterBag: '@parameter_bag'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Explicit service configurations
  App\Security\LoginSuccessHandler:
    arguments:
      - '@router.default'

  App\Controller\User\RegistrationController:
    arguments:
      $profileImageDirectory: '%profile_image_directory%'
    tags: ['controller.service_arguments']

  App\Controller\User\Admin\UserAdminController:
    arguments:
      $profileImageDirectory: '%profile_image_directory%'

  App\Controller\User\ProfileController:
    arguments:
      $profileImageDirectory: '%profile_image_directory%'

  App\Controller\User\Admin\AdminProfileController:
    arguments:
      $profileImageDirectory: '%profile_image_directory%'

  App\Service\TwilioService:
    arguments:
      $sid: '%env(TWILIO_SID)%'
      $token: '%env(TWILIO_AUTH_TOKEN)%'
      $from: '%env(TWILIO_PHONE_NUMBER)%'

  App\Service\FaceRecognitionService:
    arguments:
      $apiKey: '%facepp.api_key%'
      $apiSecret: '%facepp.api_secret%'
